# Generated by Django 2.1.4 on 2019-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerDetails',
            fields=[
                ('consumer_no', models.BigIntegerField(db_column='Consumer.No', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('mobile', models.FloatField(blank=True, db_column='Mobile', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('discom', models.TextField(blank=True, db_column='Discom', null=True)),
                ('sub_division', models.TextField(blank=True, db_column='Sub_Division', null=True)),
                ('substation', models.TextField(blank=True, db_column='SubStation', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('con_mail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('k_no', models.IntegerField(db_column='K no', primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
