# Generated by Django 2.1.4 on 2019-06-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerdetails',
            options={'managed': True},
        ),
    ]
